### ISSUE TITLE
_process_link_usage_line(s._link_usage_line,s): ValueError

### ISSUE THREAD

**Issue by bluelancer** [knowledgedefinednetworking/datanetAPI#2]
Hi! I am doing a small trail on this API with the challenge data, the trainingset:

`reader = DatanetAPI(DATASET)
it = iter(reader)

sample = next(it)`

While I got the following issue:
`Traceback (most recent call last):
  File "/proj/gnnet/WorkspaceYifei/GNNetworkingChallenge/DataExploration/datanetAPI.py", line 940, in __iter__
    self._process_link_usage_line(s._link_usage_line,s)
  File "/proj/gnnet/WorkspaceYifei/GNNetworkingChallenge/DataExploration/datanetAPI.py", line 1206, in _process_link_usage_line
    link_stat["utilization"] = float(l[i*netSize*2+j*2])
ValueError: could not convert string to float: '0.309623,0.000000,999.554671,0.309623,0.000000,1.331939,8.000000,999.554671'

Error in the file: results_50_400-2000_0_24.tar.gz   iteration: 0`

Might I am doing something wrong here?

**Comment by albert-lopez** [comment]
Hi,
Could you confirm that you are using the datanetAPI branch of the challenge2021?:[https://github.com/BNN-UPC/datanetAPI/tree/challenge2021]( https://github.com/BNN-UPC/datanetAPI/tree/challenge2021)

**Comment by bluelancer** [comment]
My bad...I was working on 'master'...Thanks for the reply and let's close this...
