### ISSUE TITLE
Unable to find the graph information file

### ISSUE THREAD

**Issue by ideafang** [knowledgedefinednetworking/datanetAPI#5]
Hola,

Thanks for your great dataload API.
But I met an error when using this code.
```python
import datanetAPI
reader = datanetAPI.DatanetAPI(data_folder="../dataset/nsfnetbw")
it = iter(reader)
for sample in it:
    print(sample.maxAvgLambda)
    exit(0)
```
and get an error like `Unable to find the graph information file`.
Then I found the code  `for root, dirs, files in os.walk(self.data_folder):` in line 635.
It will traverse all dataset subfolders including `tfrecord` dir, and it doesn't have a `graph_attr.txt` file.
So I move the `tfrecord` dir to another path and the code run.
I think this loop function should be improved because the tfrecord folder is initially in the dataset.

BR,
Henry

**Comment by MiquelFerriol** [comment]
Hi @ideafang
Thank you very much for your feedback!

Your suggestion has been implemented in the [last commit](https://github.com/BNN-UPC/datanetAPI/commit/53e81db02f5a8ad61c608f9088f9818fb2b5459f). Now the API should work properly and return all the data samples even if there are some directories inside that do not contain a graph_attr.txt file.

Bests,
Miquel

**Comment by ideafang** [comment]
Hi, Miquel
I can't get the last commit and the link may be somewhere wrong. 

BR,
Henry

**Comment by MiquelFerriol** [comment]
Hi @ideafang,
There was an error at the URL, now it is fixed.
 If you want, you can download the new version directly from the branch [here](https://github.com/BNN-UPC/datanetAPI/tree/dataset_v0).

Thanks for pointing it out!

Bests,
Miquel
